### ISSUE TITLE
build error with esbuild

### ISSUE THREAD

**Issue by yovanoc** [esfx/esfx#53]
Hi since the version prenative last week I got this:

<img width="764" alt="image" src="https://user-images.githubusercontent.com/7302317/189759434-9d278de5-7e7a-4cc2-b3d6-095db5b52be0.png">

Thanks

**Comment by rbuckton** [comment]
Have you tried a more recent version? This should be fixed in 1.0.0-pre.37

**Comment by yovanoc** [comment]
I'm not directly using esfx, I'm using your prex library. And I dont know why it's installing this version of esfx now.

**Comment by yovanoc** [comment]
<img width="659" alt="image" src="https://user-images.githubusercontent.com/7302317/189942101-564096d2-f0aa-4fb2-a148-2e6375b7c7a1.png">

**Comment by rbuckton** [comment]
I'm guessing prex is choosing those due to how semver caret ranges order the package names. I'll see if I can push up a new version of prex with a new dependency range that excludes that version.  I'd recommend you move off of `prex` anyways. I've migrated all of its functionality into various `@esfx/async-*` packages.

**Comment by rbuckton** [comment]
I just published `prex@0.4.8`, which should now exclude that version.

**Comment by yovanoc** [comment]
It does not work, but no problem was just using deferred and semaphore. You should deprecate prex I think so? Im going to switch to esfx now !

**Comment by rbuckton** [comment]
It has been deprecated.

**Comment by yovanoc** [comment]
I just switched and there is an error again.

<img width="788" alt="image" src="https://user-images.githubusercontent.com/7302317/190010805-4a7f700e-1179-4ef2-8cc7-72d0f0dc2a8d.png">

<img width="997" alt="image" src="https://user-images.githubusercontent.com/7302317/190010844-d7ae440f-961b-49c0-a576-aa7759d48764.png">


We clearly see that the import want to load an index.js but only a disposable.js exists

**Comment by rbuckton** [comment]
Unfortunately, that's still pointing at a bad copy of disposable. The `-prenative.*` prerelease version is the problem since according to semver it's considered a higher version number than `-pre.*`. This probably won't go away until I publish 1.0.0, which I won't be able to do until I am able to get linux and macos builds of the `@esfx/equatable` node bindings working. Your best bet is to pin the versions or use overrides until I can get something working in the next day or two.

**Comment by yovanoc** [comment]
Yeah I just added this to my package.json too but the problem is still here in pre 37.  In the exports field for the `"."` entry you should put disposable.js not index.js

```json
"resolutions": {
    "@esfx/async-deferred": "1.0.0-pre.37",
    "@esfx/async-semaphore": "1.0.0-pre.37",
    "@esfx/async-waitqueue": "1.0.0-pre.37",
    "@esfx/cancelable": "1.0.0-pre.37",
    "@esfx/disposable": "1.0.0-pre.37"
  },
```

**Comment by yovanoc** [comment]
I just tested your .38 and prevenative-1 and now I can build perfectly but at runtime I have this error:


<img width="1158" alt="image" src="https://user-images.githubusercontent.com/7302317/190853932-a310a4fe-6e5a-4667-bdd4-965530ba7c7c.png">

**Comment by rbuckton** [comment]
Please try with `1.0.0-pre.39` and let me know if you're still getting this error.

**Comment by yovanoc** [comment]
Yeah I had to specify resolutions still because the prenative version but yeah its working thanks
