### ISSUE TITLE
Generated esm for some modules contains `export` keyword in unexpected place

### ISSUE THREAD

**Issue by peitschie** [esfx/esfx#56]
Hi,

I've been trialing this library out with esbuild, and have found I can't really build because the generated ESM module has exports inside of nested functions for some reason. You can see in the screenshot below that TypeScript is not too happy about this export being so nested:

![image](https://user-images.githubusercontent.com/1052079/190411481-e9290d69-d043-47e7-a962-9e85ef46d2e5.png)

I've checked a few other JS syntax checkers, and most of them are quite unhappy about this syntax. Is this a library issue?

(as a long time prex user, I'm just migrating across to your shiny setup here!)

**Comment by rbuckton** [comment]
Ah, this is due to some inlining code I wrote. I'll look into that, thanks
________________________________
From: Philip Peitsch ***@***.***>
Sent: Thursday, September 15, 2022 9:10:39 AM
To: esfx/esfx ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [esfx/esfx] Generated esm for some modules contains `export` keyword in unexpected place (Issue #56)


Hi,

I've been trialing this library out with esbuild, and have found I can't really build because the generated ESM module has exports inside of nested functions for some reason. You can see in the screenshot below that TypeScript is not too happy about this export being so nested:

[image]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F1052079%2F190411481-e9290d69-d043-47e7-a962-9e85ef46d2e5.png&data=05%7C01%7Cron.buckton%40microsoft.com%7Cc85f3c37a1044cfc1efd08da971bafd2%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637988442427063658%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Lr%2Fzlj8psPfB5KhyaH0qjadXKhLLcFPxMJJDB2xCpkc%3D&reserved=0>

I've checked a few other JS syntax checkers, and most of them are quite unhappy about this syntax. Is this a library issue?

(as a long time prex user, I'm just migrating across to your shiny setup here!)

**Comment by rbuckton** [comment]
This should be fixed in 885cd2206f824d1c792f3188e91a2963ed5b6d26, but I won't have a new version ready until I'm able to finish a publish workflow that can build the linux and macos binaries for `@esfx/equatable`.
